version: 1
update_configs:
- package_manager: "java:gradle"
  directory: "/"
  update_schedule: "daily"
  target_branch: "develop"
  default_reviewers:
  - "m-ujaffer"
  - "alex-deloitte"
  default_assignees:
  - "m-ujaffer"
  - "alex-deloitte"
  allowed_updates:
  - match:
      update_type: "security"
