name: CI

on:
  push:

jobs:
  security:
    runs-on: ubuntu-latest
    uses: actions/checkout@v2
    uses: snyk/actions/gradle-jdk11@master
    with:
      args: '--all-projects'
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}