name: CI

on:
  push:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/gradle-jdk11@master
      with:
        args: '--all-projects'
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

ignore:
  'snyk:lic:maven:com.itextpdf:itextpdf:AGPL-3.0'
  reason: 'No fix available, blocks merging Snyk'